[include]
base = path_base.ini

# Bull path (paper Fig. 8) — raster scan of the longhorn image.
[path.picture]
image = ../images/longhorn.jpg
horizontal =50mm
column_res_x = 200um
column_res_y = 200um

path_name = longhorn
